- hosts: test
  tasks:
    - name: Try to find PTR record
      #curl -s https://api.hackertarget.com/reversedns/?q=195.24.66.185 | awk '{print $2}'
    - name: Make sure exim4 service is stopped
      service:
        name: exim4
        enabled: no
        state: stopped
      register: command_result
      failed_when: "command_result is failed and ('find' not in command_result.msg and 'found' not in command_result.msg)"

    - name: Make sure Exim4 is not installed
      apt:
        name: exim4
        state: absent
        autoremove: yes
        purge: yes

    - name: Make sure dependancies present
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
        - libsasl2-modules
        - libsasl2-2
        - sasl2-bin
        - netcat
        - curl


#    - name: Set Postfix option hostname
#      debconf: 
#        name: postifx 
#        question: "postfix/mailname" 
#        value: "sandbox" 
#        vtype: "string"
#
    - name: get ptr api
      uri:
        url: https://api.hackertarget.com/reversedns/?q={{ ansible_default_ipv4.address }}
        return_content: yes
      register: ptr_record


    - name: Set Postfix option hostname
      debconf:
        name: postifx
        question: "postfix/mailname"
        value: "{{ ptr_record.content.split(' ')[1] | regex_replace('\n','')}}"
        vtype: "string"
      when: ptr_record.content != "no records found"


#
    - name: Set Postfix option type as internet site
      debconf: 
        name: postfix 
        question: "postfix/main_mailer_type" 
        value: 'Internet Site' 
        vtype: "string"

    - name: install postfix
      apt: 
        name: postfix
        state: present

    - name: Make sure local user exists
      user:
        name: user
        state: present
        create_home: no
        password: "$6$mysecretsalt$Gf6liusyPHJn5doRrgRIqmxYe6fSxliL3sTdFacyx93Ti9XQSHGpiMOYEKyefDJz.YYBQn/QeqGznhmCLEDHo/"
        append: yes
        groups: sasl,postfix

    - name: Make sure folder /var/spool/postfix/var/run/saslauthd exists
      file:
        path: /var/spool/postfix/var/run/saslauthd
        state: directory
        mode: 0755

    - name: Saslauthd config [mechanism]
      lineinfile:
        path: /etc/default/saslauthd
        state: present
        regexp: '^MECHANISMS='
        line: 'MECHANISMS="shadow"'
      notify:
        - restartSasl

    - name: Saslauthd config [options]
      lineinfile:
        path: /etc/default/saslauthd
        state: present
        regexp: '^OPTIONS='
        line: 'OPTIONS="-c -m /var/spool/postfix/var/run/saslauthd"'
      notify:
        - restartSasl
   
    - name: Saslauthd config [startup]
      lineinfile:
        path: /etc/default/saslauthd
        state: present
        regexp: '^START='
        line: 'START=yes'
      notify:
        - restartSasl

    - name: postfix config /etc/postfix/main.cf
      blockinfile:
        insertafter: EOF
        path: /etc/postfix/main.cf
        state: present
        block: |
          #smtp_bind_address=x.x.x.x
          #SASL
          smtpd_sasl_local_domain = $myhostname
          smtpd_sasl_auth_enable = yes
          broken_sasl_auth_clients = yes
          smtpd_sasl_authenticated_header = no
          smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination
          #header_checks = regexp:/etc/postfix/header_checks
          #
          #Backoff
          #
          #How long a message stays in the queue before it is sent back as undeliverable.(days)
          maximal_queue_lifetime=1
          #The minimal amount of time a message won't be looked at,
          # and the minimal amount of time to stay away from a "dead" destination. (seconds)
          minimal_backoff_time=600
          maximal_backoff_time=900
          bounce_queue_lifetime=0
          inet_protocols = ipv4
      notify:
        - restartPostfix
    
    - name: postfix config /etc/postfix/master.cf
      lineinfile:
        path: /etc/postfix/master.cf
        state: present
        line: '3077    inet    n       -       y       -       -       smtpd'
      notify:
        - restartPostfix
    
    - name: postfix config auth 
      blockinfile:
        path: /etc/postfix/sasl/smtpd.conf
        create: yes
        state: present
        block: |
          pwcheck_method: saslauthd
          mech_list: PLAIN LOGIN
      notify:
        - restartPostfix

    - name: crontab vars
      cronvar:
        name: MAILTO
        value: '""'
        state: present

    - name: crontab jobs
      cron:
        name: ClearQueue
        minute: '*/5'
        job: '/usr/sbin/postsuper -d ALL deferred'
        state: present

    - name : crontab jobs
      cron:
        name: RestartPostfix
        minute: 0
        hour: 11
        weekday: 0
        job: '/etc/init.d/postfix stop; rm -r /var/spool/postfix/defer/* ; /etc/init.d/postfix start'

  handlers:
    - name: restartPostfix
      service:
        name: postfix
        state: restarted
    - name: restartSasl
      service:
        name: saslauthd
        state: restarted