- hosts: test
  tasks:
    - name: Make sure exim4 service is stopped
      service:
        name: exim4
        enabled: no
        state: stopped
      register: command_result
      failed_when: "command_result is failed and ('find' not in command_result.msg and 'found' not in command_result.msg)"

    - name: Make sure Exim4 is not installed
      apt:
        name: exim4
        state: absent
        autoremove: yes
        purge: yes

    - name: Make sure dependancies present
      apt:
        update_cache: yes
        name: {{item}}
        state: present
        with_items:
          - libsasl2-modules
          - libsasl2-2
          - sasl2-bin
          - netcat


#    - name: Set Postfix option hostname
#      debconf: 
#        name: postifx 
#        question: "postfix/mailname" 
#        value: "sandbox" 
#        vtype: "string"

    - name: Set Postfix option type as internet site
      debconf: 
        name: postfix 
        question: "postfix/main_mailer_type" 
        value=: 'Internet Site' 
        vtype: "string"

    - name: install postfix
      apt: 
        name: postfix
        state: present

    - name: Make sure local user exists
      user:
        name: user
        state: present
        create_home: no
        password: "$6$mysecretsalt$Gf6liusyPHJn5doRrgRIqmxYe6fSxliL3sTdFacyx93Ti9XQSHGpiMOYEKyefDJz.YYBQn/QeqGznhmCLEDHo/"
        append: yes
        groups: sasl,postfix

    